# Generated by Django 5.1.5 on 2025-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_accidentreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambulance",
            name="address",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
