# Generated by Django 5.1.2 on 2025-02-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_ambulance_address_alter_ambulance_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentreport",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="latitude",
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="longitude",
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name="admin",
            name="last_activity",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
