# Generated by Django 5.1.4 on 2025-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_accidentreport_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentreport",
            name="severity",
            field=models.CharField(
                choices=[("BASIC", "Basic"), ("UCI", "UCI")],
                default="BASIC",
                max_length=5,
            ),
        ),
    ]
