# Generated by Django 5.1.4 on 2025-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_accidentreport_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentreport",
            name="resolved_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
