# Generated by Django 5.1.4 on 2025-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_accidentreport_resolved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentreport",
            name="assigned_ambulance_user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
