# Generated by Django 5.1.4 on 2025-05-20 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_ambulance_email_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="level_of_care",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.AddField(
            model_name="accidentreport",
            name="additional_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accidentreport",
            name="caller_phone_number",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="accidentreport",
            name="people_involved",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="accidentreport",
            name="reference_point",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accidentreport",
            name="type_place",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Public road"),
                    (2, "Building"),
                    (3, "Institution"),
                    (4, "Rural area"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="classification",
            field=models.SmallIntegerField(
                choices=[(1, "Public"), (2, "Private"), (3, "Mixed")], default=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "First level"), (2, "Second level"), (3, "Third level")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="full_name",
            field=models.CharField(default="Nombre no identificado", max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="glasgow",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MaxValueValidator(15),
                    django.core.validators.MinValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="id_number",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_record",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[("S", "Stable"), ("C", "Critical"), ("U", "Unconscious")],
                default="S",
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="latitude",
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="longitude",
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="resolved_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="severity",
            field=models.CharField(
                choices=[("BASIC", "Basic"), ("UCI", "UCI")], default="BASIC"
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="address",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="latitude",
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="longitude",
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ambulance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.ambulance",
            ),
        ),
    ]
