# Generated by Django 5.1.2 on 2025-08-25 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_hospital_level_of_care_remove_patient_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentreport",
            name="assigned_ambulance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.ambulance",
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="assigned_ambulance_user_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
