# Generated by Django 5.1.15 on 2026-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_accidentreport_assigned_ambulance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentreport",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
