# Generated by Django 5.1.5 on 2025-01-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticationapi", "0002_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambulance",
            name="assigned_hospital",
        ),
        migrations.RemoveField(
            model_name="ambulance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="ambulance",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="user",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="Ambulance",
        ),
        migrations.DeleteModel(
            name="Hospital",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
